# taken from https://qiita.com/KumanoT/items/11e4315f4623291274c0
version: '3'

services:
  kafka:
    image: confluentinc/cp-kafka:5.3.2
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_NUM_PARTITIONS: 3
      CONFLUENT_SUPPORT_METRICS_ENABLE: 0
    ports: ["9092:9092"]
    links: [zookeeper]
    volumes:
      - ./docker-compose-data/kafka:/var/lib/kafka/data
  zookeeper:
    image: confluentinc/cp-zookeeper:5.3.2
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports: ["2181:2181"]
    volumes:
      - ./docker-compose-data/zookeeper/data:/var/lib/zookeeper/data
      - ./docker-compose-data/zookeeper/log:/var/lib/zookeeper/log